# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a9d4e42b260ea994afd8490b74947ce9f4eedde8715f365f960ca3bcaa09fbeb80e916cd9dc044642fd73139dfefe44bf56579f16a55b2db772a64502dd1766

test:
  secret_key_base: 7d99d7dad5b485e1d841a63fe48b0b977f4b56629fe3720ec64fe0b84012f00711902a81ced46235d5f9d6915af6629b6c008fa60eaebf5e603ddfe8fd06009c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
